appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32ce7dc05bae0700d32b56
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: hVL+HrVcy9SKISQqaskgtVIn5SNAVCRZLaC+RxUmY3fSDO4X2F5+F0bUhPIU8q5vVY1DLSA20xAEsFbqSLO+ToOcgCPT1q1Ky5ZbJWaHcMicpWd+2SCAY9af//mmWLieuvspQcRUPpM9H6kA8qUNH3pm5uKjZQZWfkm/N6X5nAyKUrKTDhEsaeA01u0tJtWxfKaEerztRwOlD40ZO3OEDPARggcgveihDiDbDJ3AANxxuviPig27Tg0eD3C/9jBryWyBYEupCR70w3QkG+tUqQ//rR6Ucu4dlLN2hzTmiIMRnHSko4gfTC2pNV65PhEedWIirsYVikzDeg7QOnRKPTFB9HRv4hFxFwyr/iNjhIJoNwlx4g/tpxCW/2oHVwwrpfqNaS4d339ezUgjjIMnAXEpMDtbLRNzRCaC7liNlJKZeTy0ypGWCo1JvLxtL8QDExUcyvveHOd01tk6zEk7qwfar10j659eZmJtrteClqFxXgCZZ8XT8y8L5wntenz4ycQzL9YgHSjvt5GHQduveQFj7dSGZhKe/epNNqIQQmUjhfzKAS5g/11G+LPchlzYVcTdsi19yiGu1Vy6SUSBYOyHhPFGgmZfMhnQo0pRLSnw9irbNqH3xYFP3aEtEg5xiIpI/m3nzGaOQDQAOWNWCYcgB2C+v+L+2fnwxgB9g0o=}
